# Generated by Django 4.1.7 on 2023-07-09 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_chatroom_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='Author',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
