# Generated by Django 4.1.7 on 2023-07-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_chatroom_author_chatroom_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='author',
            new_name='Author',
        ),
    ]
