# Generated by Django 4.1.7 on 2023-08-04 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_userprofile_friends_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='friends_added',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None),
        ),
    ]
