# Generated by Django 4.1.7 on 2023-07-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ChatRoom',
            new_name='chatroom',
        ),
    ]
