# Generated by Django 4.1.7 on 2023-08-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='testingArray',
        ),
    ]
