# Generated by Django 4.1.7 on 2023-07-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_content_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
