# Generated by Django 4.1.7 on 2023-08-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_test_testingarray'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testingArray',
        ),
    ]
